name: CI
on: [push, pull_request]
jobs:
  build:
  strategy:
      matrix:
        os: [windows-latest, windows-2016]
    
    steps:
    - uses: actions/checkout@v2
    name:  BuildThirdPartyDependencies
      BuildThirdPartyDependencies.bat
    name: Build
      cd “C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\”
      .\MSBuild.exe CppCoverage.sln
  